const mongoose = require('mongoose')

const eventSchema = new mongoose.Schema({
  slug: { type: String, required: true, unique: true },
  title: { type: String, required: true },
  tagline: String,
  description: String,
  coverImage: String,
  date: Date,
  endDate: Date,
  time: String,
  endTime: String,
  venue: String,
  address: String,
  city: String,
  state: String,
  country: String,
  isVirtual: { type: Boolean, default: false },
  virtualLink: String,
  category: String,
  status: { type: String, enum: ['draft', 'published', 'cancelled'], default: 'draft' },
  organizerId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  organizerName: String,
  organizerLogo: String,
  organizerDescription: String,
  maxAttendees: Number,
  registeredCount: { type: Number, default: 0 },
  checkedInCount: { type: Number, default: 0 },
  revenue: { type: Number, default: 0 },
  hasExam: { type: Boolean, default: false },
  hasCertificate: { type: Boolean, default: false },
  speakers: [Object],
  sponsors: [Object],
  partners: [Object],
  agenda: [Object],
  faq: [Object],
  tickets: [Object],
  registrationFields: [Object],
}, { timestamps: true })

module.exports = mongoose.model('Event', eventSchema)